biocore/calour

.travis.yml, COPYING.txt, Makefile, README.md, calour/__init__.py, calour/study.py, ci/conda_requirements.txt, ci/pip_requirements.txt, setup.cfg, setup.py
@amnona, let's start populating it!
=> init setup

calour/study.py
@amnona , this is the example you wanted. could you write the tests with your small data set?
=> implement reorder()

calour/plotting.py, calour/tests/test_plotting.py, calour/tests/test_transforming.py, calour/transforming.py
@amnona @mortonjt , could any of you review this PR?
=> add subsample function

calour/experiment.py, calour/heatmap/heatmap.py
Note the legend fix is not an ideal solution because the color bar will overlap
with the feature colorbar if it is plotted.
=> fix a minor bug and prettify the heatmap legend of colorbar

calour/heatmap/heatmap.py, calour/heatmap/plotgui.py, calour/heatmap/tests/test_heatmap.py
fix the problems from previous commit on legend of colorbar
=> add an extra axes to plot the legend of colorbar

calour/tests/test_transforming.py, calour/transforming.py
=> make centralize an option in center_log

calour/__init__.py, calour/_doc.py, calour/amplicon_experiment.py, calour/doc_init.py, calour/experiment.py, calour/filtering.py, calour/heatmap/heatmap.py, calour/heatmap/plotgui.py, calour/heatmap/plotgui_cli.py, calour/heatmap/plotgui_jupyter.py, calour/heatmap/plotgui_qt5.py, calour/io.py, calour/manipulation.py, calour/plotting.py, calour/sorting.py, calour/tests/test_filtering.py, calour/tests/test_manipulation.py, calour/tests/test_plotting.py, calour/tests/test_training.py, calour/training.py, calour/transforming.py, calour/util.py
=> add a couple functions

calour/amplicon_experiment.py, calour/experiment.py, calour/filtering.py, calour/io.py, calour/manipulation.py, calour/plotting.py, calour/tests/test_amplicon_experiment.py, calour/tests/test_filtering.py, calour/tests/test_io.py, calour/transforming.py, calour/util.py, doc/source/conf.py
=> refactor filter abundance functions

calour/filtering.py, calour/tests/test_filtering.py
the fraction param was not passed
=> fix a bug in filter_prevalence

calour/tests/test_filtering.py, calour/tests/test_training.py, calour/training.py
and small changes in plot_cm()
=> add more filtering tests

calour/plotting.py
`calour.plotting.plot_stacked_bar` was missing some functionalities available in `Experiment.plot`, so I added them
=> ENH: plot_stacked_bar

calour/amplicon_experiment.py, calour/analysis.py, calour/filtering.py, calour/heatmap/plotgui_jupyter.py, calour/heatmap/plotgui_qt5.py, calour/tests/test_training.py, calour/training.py
also fix a bug of typo and update the deprecated logger.warn to logger.warning
=>  improve plot_roc()

calour/experiment.py, calour/filtering.py, calour/manipulation.py
the old dtype is not big enough
=> fix a bug a aggregate_by_metadata

calour/dsfdr.py, doc/source/notebooks/metabolome_gnps.ipynb
fix issue [#146](https://github.com/biocore/calour/issues/146)
=> Fix metabolome notebook

calour/io.py, calour/tests/test_training.py, calour/training.py
The original tests cause error because of randomness.
=> update (Repeated)SortedStatifiedKFold unit tests

calour/manipulation.py, calour/tests/test_manipulation.py
add align parameter to join_metadata_fields function
=> add align parameter to join_metadata_fields function

calour/io.py, calour/tests/test_training.py, calour/training.py
in the (Repeated)SortedStratifiedKFold.
=> suppress unintended warning from sklearn

calour/analysis.py, calour/dsfdr.py, calour/filtering.py, calour/plotting.py, calour/tests/test_analysis.py, calour/tests/test_dsfdr.py, calour/tests/test_filtering.py, calour/tests/test_plotting.py, calour/tests/test_transforming.py, calour/training.py
In calour.analysis change random_seed (which was used for random.seed() ) to random_state.
also, added random_state to dsfdr(), and it is passed from the analysis functions.
* Now all of calour except transforming.subsample_count() uses random_state
=> change random_seed to random_state

calour/tests/test_transforming.py, calour/transforming.py
Move skbio imports in transforming.py optional
=> make skbio dependance optional

calour/experiment.py, calour/tests/test_experiment.py
and unit tests.
Only thing open is how to make calour parse the axis='s' when calling this iterator, @RNAer any idea?
=> add Experiment.iterate()

calour/experiment.py, calour/manipulation.py, calour/sorting.py, calour/tests/test_sorting.py
cluster_feature() shouldn't transform the data table.
=> fix cluster_features() bug

CHANGELOG.md, calour/transforming.py
Add random_seed to permute_data()
=> add random_seed to permute_data

calour/experiment.py, calour/ratio_experiment.py, calour/sorting.py, calour/util.py
=> move reorder() to avoid `axis` function argument not converted and avoid its running not recorded 

calour/experiment.py, calour/ms1_experiment.py, calour/ratio_experiment.py, calour/tests/test_experiment.py, doc/source/notebooks/metabolome_gnps.ipynb
So now exp.iterate() yields the value and the experiment subset.
For example:
exp.iterate('gender')
yields
'male', Experiment (with all male samples)
'female', Experiment (with all female samples)
=> add value to Experiment.iterate()

calour/heatmap/plotgui.py
add cmd+click equivalent to super+click for interactive heatmap
=> add cmd+click to selection

calour/manipulation.py
fix bug:"numpy.ndarray" object has no attribute "median"
=> fix bug:"numpy.ndarray" object has no attribute "median"

calour/analysis.py
Fixed a bug where diff_abundance_paired would fail if the 2 values (val1, val2) did not cover all the samples.
This happened since we set up the _pair_shuffler in diff_abundance_paired() but did the sample filtering (according to val1,val2) later in diff_abundance()
So the fix now does the sample filtering in diff_abundance_paired()
=> fix bug when not using all samples in paired test

CHANGELOG.md, calour/analysis.py, calour/filtering.py, calour/io.py, calour/plotting.py
* Add better reporting to filter_by_data() and various diff abundance methods
* add sanity checks to diff abundance methods
* remove old parameter doc
=> Update reporting to diff abundance and filtering

calour/io.py
Info about the loaded experiment (how many samples/features)
=> add info after loading an experiment

CHANGELOG.md, calour/analysis.py, calour/database.py, calour/experiment.py, calour/filtering.py, calour/heatmap/heatmap.py, calour/io.py, calour/plotting.py, calour/transforming.py, calour/util.py
Add type hints to return values of additional calour functions
Add initialization of Experiment.info dict if not provided as a parameter to calour.Experiment()
NOTE: in database.py, moved the _get_database_class() method to after the class declaration so can define the return type
=> add type hints

CHANGELOG.md, calour/analysis.py, calour/database.py, calour/experiment.py, calour/filtering.py, calour/heatmap/heatmap.py, calour/heatmap/plotgui.py, calour/io.py, calour/plotting.py, calour/transforming.py, calour/util.py
* add some more type hints
* create hashes if not provided in new experiment
* bugfix update remove lines for mpl3.7
* update changelog
=> Mpl37fix (#63)

CHANGELOG.md, calour/__init__.py, calour/analysis.py, calour/experiment.py
Fix bug in diff_abundance() that would raise an exception if column was all numeric
bump version
update changelog
=> Bugfix diff abundance

CHANGELOG.md, calour/__init__.py, calour/calour.config, calour/mrna_experiment.py
add mRNAExperiment class for RNA-seq experiments
currently just supports interactive heatmap gene-name to function information display
=> mRNA experiment support
