biocore/calour

calour/io.py, calour/plotting.py, calour/sorting.py, calour/tests/test_amplicon_experiment.py, calour/tests/test_analysis.py, calour/tests/test_database.py, calour/tests/test_io.py, calour/tests/test_plotting.py
rename "filter_reads" to "min_reads". The original name is confusing to me. I have to check if it filters out samples or reads every time
unset default for `min_abundance` in cluster_features, because it may go unnoticed too easily, which may cause problem if it is not normalized to 10k.
=> fix a bug in plot_shareness

calour/heatmap/heatmap.py, calour/util.py
If a dict given to `barx_colors`, the dict was converted to list of
its keys and color info was lost in bar plotting. The problem is that
`_to_list` should convert a dict to a list of dict.
=> fix a bug of colors x/y bars for heatmap

calour/_testing.py, calour/experiment.py, calour/tests/test_experiment.py
calour/experiment.py: use pandas.DataFrame.sparse.from_spmatrix function instead of pandas.SparseDataFrame.
calour/test/test_experiment.py: can not assert a dataframe to SparseDataFrame any longer,  so choose one row in the dataframe to assert if it is sparse form;  use pandas.testing instead of pandas.util.testing.
calour/_test.py: use pandas.testing instead of pandas.util.testing.
=> modify experiment.py, test_experiment.py, _test.py for pandas.SparseDataFrame and pandas.util.testing are deprecated

calour/calour.config, calour/database.py, calour/heatmap/heatmap.py, calour/tests/test_database.py
Instead of raising an error, just warn the user and provide database interface installation instructions.
* Added installation, website and description to each database section in the calour.config file
* Added phenodb to config file
=> make database not installed warn instead of raise error

calour/heatmap/plotgui_qt5.py
each database module should have it's own qt5 gui implementation via "show_enrichment_qt5()" function
=> move qt5 term enrichment gui to database modules

calour/dsfdr.py, calour/tests/test_dsfdr.py
Change the mann-whitney statit to use two-sided instead of the previous default None (which is depracated)
=> fix mannwhitney warning

calour/amplicon_experiment.py, calour/calour.config, calour/database.py, calour/experiment.py, calour/heatmap/heatmap.py, calour/heatmap/plotgui.py, calour/heatmap/plotgui_qt5.py, calour/tests/mock_database.py, calour/tests/test_database.py
Make database interface compatible with the new database metadata structure:
* convert Experiment.databases to defaultdict(dict). i.e. for dbbact data is stored in exp.databases['dbbact']
* add minimal version support to database config file and test it
=> Dbbact metadata

CHANGELOG.md, calour/heatmap/heatmap.py
Add an option to specify a different color for the colormap.bad_color().
Used to be hard-set in the heatmap() code to 'black'. But sometimes we want a different color for the nans.
While we could use the bad_color set in the colormap parameter, problem is the default bad_color() (at least for viridis) is 'white', which does not look good (since all the 0s are log transformed to nans)
also updated changelog
=> Heatmap nan

calour/io.py, calour/ms1_experiment.py, calour/tests/test_io.py, calour/tests/test_ms1experiment.py, calour/transforming.py
Add some utility functions to ms1experiment:
* filter_mz() - for approximate m/z filtering
* get_bad_features() - for detection of feature-selection artifacts
* improve the heatmap() for nice ms1 defaults (show mz/rt on y-axis)
=> Ms1 experiment

calour/heatmap/plotgui_qt5.py
fix the debugging message in right_menu_remove_feature
(called when right clicking on a feature and selecting remove from annotation)
=> fix debug message in delete sequence from annotation

calour/export_html_template.html, calour/tests/data/export_html_result.html
So will work when embedded in https page (such as qiime2 view)
=> make html export use https for obtaining dsj3

calour/calour.config, calour/database.py
Moved dbbact-calour version numbers to semantic versioning (i.e. '1.4.1')
Added support for parsing these version numbers when getting the minimal database version from the calour.config file.
If database version is lower than the recommended version in the calour.config, it displays a warning to the user
Also updated calour.config for the new semantic versioning minimal recommended dbbact-calour version (1.4)
=> Dbbact version

calour/database.py
Fix the dbbact-calour version checking to use packaging.version.parse()
=> fix dbbact-calour version testing

calour/export_html_template.html
dbbact now works https
converting exported heatmap query links to https (since we get mixed content warning if query using http from an https page)
=> feat: support https on the exported heatmap

calour/io.py
Fix a problem when a doing read_ms1() on a biom file with sample_in_row=True (it ignored it).
Also, removed the "transpose" parameters we had in _read_biom(), which should always be true (since biom is transposed compared to what we use in calour).
=> Fix sample_in_row for read_ms

CHANGELOG.md, calour/__init__.py, calour/manipulation.py
the default should be 0 rather than 's' since the conversion from 's'->0 is performed if the parameter is supplied (not on the default)
=> fix join_metadata() and version bump

CHANGELOG.md, calour/io.py
Instead of giving a warning with all the missing sample data/metadata, show only a summary and first 5 samples without data/metadata.
The full list of problematic samples is available as a debug() level message.
=> fix _read_metadata() to show as warning/info only the summary 

CHANGELOG.md, calour/__init__.py, calour/manipulation.py
* Change default join_metadata_fields() inplace parameter to False
* Fix join_experiments() to update exp.info['sample_metadata_md5'] and exp.info['data_md5']
* Fix join_experiments() to make field parameter optional, enable joining when field already exists in the experiment, and update the doc
* Fix join_experiments_featurewise() to make field parameter optional, enable joining when field already exists in the experiment, and update the doc
and update the changelog
=> Bugfixes for manipulation.py

CHANGELOG.md, calour/heatmap/heatmap.py
copy the colormap so we don't modify in place (otherwise we get a matplotlib deprecation warning)
=> fix heatmap() inplace colormap modification depracation warning

CHANGELOG.md, calour/filtering.py
To prevent the warning when reading an experiment
=> remove normaliztion check warning from filter_by_data()

calour/plotting.py
* Add option to specify the bary_labels style kwargs and the within-bar (num enriched experiments) text style kwargs
* Add warning if (usually due to bad background script in dbBact) term does not have total_experiments count
=> Better diff_abundance_enrichment() plot

calour/io.py
so can specify a different separator for the metadata when reading an experiment
=> enable sep=XX parameter in _read_metadata()

CHANGELOG.md, calour/analysis.py, calour/database.py, calour/experiment.py, calour/filtering.py, calour/heatmap/heatmap.py, calour/heatmap/plotgui.py, calour/io.py, calour/plotting.py, calour/transforming.py, calour/util.py
* Add type hints to methods
* Bugfix - fix the interactive heatmap so will work with matplotlib > 3.7 (problem with Axes.lines.remove in mpl3.7)
* Add md5 hash for the sample metadata dataframe if Experiment created from dataframes
=> Mpl37 plot fix and additional type hints for methods

CHANGELOG.md, calour/__init__.py, calour/experiment.py, calour/heatmap/heatmap.py
* add support for supplying lists (of sample/feature IDs) instead of pd.DataFrame to Experiment.__init__(). Useful since otherwise need to create a Dataframe with index and appropriate field ('SampleID' or '_feature_id') in order to work.
* Raise an error when plotting an empty Experiment (otherwise raises an error downstream when trying to get the vmin/vmax).
=> Small Fixes
